### ISSUE TITLE
to.meta.isSecret isn't set to rue in even one route

### ISSUE THREAD

**Issue by jewpaltz** [meganschmidt23/WebServerApp-Schmidt-Megan#4]
https://github.com/meganschmidt23/WebServerApp-Schmidt-Megan/blob/3cc7d43db5268532d14400b60b70405964e14b5c/client/src/router/index.js#L85

You copied this code from my router but you never used it.
Not one page - even `DiscussionBoard` - is requiring a log in.

**Comment by meganschmidt23** [comment]
Professor Plotkin,

This was an honest mistake. I forgot to change them back to true after converting everything from the client side to the server side. I changed them to false to make it easier to make changes while working on the server and the client sides.

Megan
